Feat/tmp from weather
jphacks/B_2207 pull request #12
Opened 2022-10-16 08:45 UTC by 19-yamamoto

・天気APIから体感温度を取得するとこまでやった（weather.pyが該当）
・実際に使用する体感温度は一日の中の体感温度の最低値だろうという結論にいたりそれを取得するコードになってる
・細かいことはコードに書いてあるのでわかりにくいところがあったら連絡頼む

2022-10-16 09:11 UTC, Mishima-Ryuji commented
Poetryで追加されていないのではないかな？READMEを読んで，Poetry環境に適用お願いします．

また，APIのアクセストークンは直書きするのはあまり良くないので，config/settingにあるところで環境変数の読み込みに切り替えましょう．環境変数は.envファイルに追加して，Slackでみんなに共有する感じが良いね．

あとディレクトリ構造だけど，weatherの中に体感温度の取得を入れるのは良いと思うんだけど，服装の探索までは入れないほうが良いと思う．服装の選択は，READMEに書いてあるように，recommernder内のsearcherに書いてくれると助かる．

2022-10-16 09:12 UTC, Mishima-Ryuji commented
あとファイルは，hogehoge_hugahugaという形式でアンダースコア区切りで統一お願いします．

2022-10-16 09:14 UTC, Mishima-Ryuji requested changes
コメントした点の確認をよろしくおねがいします．

2022-10-17 11:38 UTC, Mishima-Ryuji requested changes

2022-10-17 11:38 UTC, Mishima-Ryuji commented on weather/weatherAPI.py
> +API_TOKEN = Setting().wapi #環境変数を使う場合（実行する際ディレクトリの場所をconfigの位置に設定しないとエラーが出る）
これでやれば回避できないかな？
https://note.nkmk.me/python-relative-import/

rootディレクトリで実行できないと，結構不便利なるので確認して貰えると助かる．

2022-10-17 11:38 UTC, Mishima-Ryuji commented on weather/weatherAPI.py
> +place =  str(input()) # 暫定として47都道府県をターミナルで入力する形を取った
関数化して引数で受け取るようにできるかな？

2022-10-17 11:38 UTC, Mishima-Ryuji commented on weather/weatherAPI.py
> +print(min_feel_tmps)
これを関数の返り値にしてほしい．他の関数から体感気温を取得したいので...

2022-10-17 13:59 UTC, 19-yamamoto commented on weather/weatherAPI.py
> +place =  str(input()) # 暫定として47都道府県をターミナルで入力する形を取った
出来たはず

2022-10-17 14:00 UTC, 19-yamamoto commented on weather/weatherAPI.py
> +print(min_feel_tmps)
関数化できたはず

2022-10-18 04:40 UTC, 19-yamamoto commented on weather/weatherAPI.py
> +API_TOKEN = Setting().wapi #環境変数を使う場合（実行する際ディレクトリの場所をconfigの位置に設定しないとエラーが出る）
rootディレクトリで実行できるように出来た

2022-10-19 15:51 UTC, closed without merging